<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:osd="urn:ebx-schemas:common_1.0" xmlns:fmt="urn:ebx-schemas:format_1.0" xmlns:ebxbnd="urn:ebx-schemas:binding_1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ebxs="urn:ebx-schemas:session_1.0">
    <xs:import namespace="urn:ebx-schemas:common_1.0" schemaLocation="https://schema.orchestranetworks.com/common_1.0.xsd"/>
    <xs:import namespace="urn:ebx-schemas:session_1.0" schemaLocation="https://schema.orchestranetworks.com/session_1.0.xsd"/>
    <xs:annotation>
        <xs:appinfo>
            <osd:validation/>
            <osd:inheritance>
                <dataSetInheritance>all</dataSetInheritance>
            </osd:inheritance>
            <ebxbnd:binding targetDirectory="../manufacturing-lib/src/main/java">
                <javaPathConstants typeName="com.onebx.ebx.fasttrack.manufacturing.path.ManufacturingPaths">
                    <nodes root="/root" prefix="" relativeToRoot="false"/>
                </javaPathConstants>
            </ebxbnd:binding>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="root" osd:access="--">
        <xs:complexType>
            <xs:sequence>
                <!-- Product Table -->
                <xs:element name="Product" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Products</osd:label>
                            <osd:description>Products</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Produits</osd:label>
                            <osd:description>Produits</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/productId </primaryKeys>
                                <defaultLabel>${./productId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="productId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for Product.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour Product.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="productType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Type</osd:label>
                                        <osd:description>Product Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de produit</osd:label>
                                        <osd:description>Type de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <container>MfgProductReference</container>
                                                <branch>BMfgProductReference</branch>
                                                <tablePath>/root/RefProductType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="productStatus" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Status</osd:label>
                                        <osd:description>Product Status</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Statut de produit</osd:label>
                                        <osd:description>Statut de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <container>MfgProductReference</container>
                                                <branch>BMfgProductReference</branch>
                                                <tablePath>/root/RefProductStatus</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="baseUnitOfMeasure" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Base Unit of Measure</osd:label>
                                        <osd:description>Base Unit of Measure</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Unité de mesure de base</osd:label>
                                        <osd:description>Unité de mesure de base</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <container>UOM</container>
                                                <branch>UOM</branch>
                                                <tablePath>/root/UOM</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <container>CommonReferenceData</container>
                                                <branch>CommonReferenceData</branch>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="createdBy" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Created By</osd:label>
                                        <osd:description>Record creator username.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Créé par</osd:label>
                                        <osd:description>Créateur de l'enregistrement.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="createdDate" type="xs:dateTime" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Created Date</osd:label>
                                        <osd:description>Audit timestamp recording creation time.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Date de création</osd:label>
                                        <osd:description>Date d'enregistrement de la création.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="lastUpdatedBy" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Last Updated By</osd:label>
                                        <osd:description>Audit username of last update.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Mis à jour par</osd:label>
                                        <osd:description>Dernier modificateur.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="lastUpdatedDate" type="xs:dateTime" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Last Updated Date</osd:label>
                                        <osd:description>Audit timestamp of last update.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Date de mise à jour</osd:label>
                                        <osd:description>Date de dernière modification.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- ProductionLine Table -->
                <xs:element name="ProductionLine" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Production Lines</osd:label>
                            <osd:description>Production Lines</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Lignes de production</osd:label>
                            <osd:description>Lignes de production</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/productionLineId </primaryKeys>
                                <defaultLabel>${./productionLineId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="productionLineId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductionLine.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductionLine.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="productionAreaId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Production Area</osd:label>
                                        <osd:description>Production Area</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Zone de production</osd:label>
                                        <osd:description>Zone de production</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgSitePlantManagement</branch>
                                                <container>MfgSitePlantManagement</container>
                                                <tablePath>/root/ProductionArea</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="lineName" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Line Name</osd:label>
                                        <osd:description>Line Name</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Nom de la ligne</osd:label>
                                        <osd:description>Nom de la ligne</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>
                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- WorkOrder Table -->
                <xs:element name="WorkOrder" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Work Orders</osd:label>
                            <osd:description>Work Orders</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Ordres de fabrication</osd:label>
                            <osd:description>Ordres de fabrication</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/workOrderId </primaryKeys>
                                <defaultLabel>${./workOrderId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="workOrderId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for WorkOrder.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour WorkOrder.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="variantId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Variant (SKU)</osd:label>
                                        <osd:description>Product Variant (SKU)</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Variante de produit (SKU)</osd:label>
                                        <osd:description>Variante de produit (SKU)</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantManagement</branch>
                                                <container>MfgProductVariantManagement</container>
                                                <tablePath>/root/ProductVariant</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="productionLineId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Production Line</osd:label>
                                        <osd:description>Production Line</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Ligne de production</osd:label>
                                        <osd:description>Ligne de production</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgSitePlantManagement</branch>
                                                <container>MfgSitePlantManagement</container>
                                                <tablePath>/root/ProductionLine</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="quantity" type="xs:int" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Quantity</osd:label>
                                        <osd:description>Quantity</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Quantité</osd:label>
                                        <osd:description>Quantité</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="startDate" type="xs:date" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Scheduled Start Date</osd:label>
                                        <osd:description>Scheduled Start Date</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Date de début planifiée</osd:label>
                                        <osd:description>Date de début planifiée</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="endDate" type="xs:date" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Scheduled End Date</osd:label>
                                        <osd:description>Scheduled End Date</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Date de fin planifiée</osd:label>
                                        <osd:description>Date de fin planifiée</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="workOrderStatus" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Status</osd:label>
                                        <osd:description>Status</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Statut</osd:label>
                                        <osd:description>Statut</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgWorkOrderReference</branch>
                                                <container>MfgWorkOrderReference</container>
                                                <tablePath>/root/RefWorkOrderStatus</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>
                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
