<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:osd="urn:ebx-schemas:common_1.0" xmlns:fmt="urn:ebx-schemas:format_1.0" xmlns:ebxbnd="urn:ebx-schemas:binding_1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ebxs="urn:ebx-schemas:session_1.0">
    <xs:import namespace="urn:ebx-schemas:common_1.0" schemaLocation="https://schema.orchestranetworks.com/common_1.0.xsd"/>
    <xs:import namespace="urn:ebx-schemas:session_1.0" schemaLocation="https://schema.orchestranetworks.com/session_1.0.xsd"/>
    <xs:annotation>
        <xs:appinfo>
            <osd:validation/>
            <osd:inheritance>
                <dataSetInheritance>all</dataSetInheritance>
            </osd:inheritance>
            <ebxbnd:binding targetDirectory="../manufacturing-lib/src/main/java">
                <javaPathConstants typeName="com.onebx.ebx.fasttrack.manufacturing.path.MfgProductVariantManagementPaths">
                    <nodes root="/root" prefix="" relativeToRoot="false"/>
                </javaPathConstants>
            </ebxbnd:binding>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="root" osd:access="--">
        <xs:complexType>
            <xs:sequence>
                <!-- ProductVariant Table -->
                <xs:element name="ProductVariant" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Product Variants (SKUs)</osd:label>
                            <osd:description>Product Variants (SKUs)</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Variantes de produit (SKUs)</osd:label>
                            <osd:description>Variantes de produit (SKUs)</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/variantId </primaryKeys>
                                <defaultLabel>${./variantId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="variantId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductVariant.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductVariant.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="productId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product</osd:label>
                                        <osd:description>Product</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Produit</osd:label>
                                        <osd:description>Produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductManagement</branch>

                                                <container>MfgProductManagement</container>
                                                <tablePath>/root/Product</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="variantStatus" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Variant Status</osd:label>
                                        <osd:description>Variant Status</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Statut de variante</osd:label>
                                        <osd:description>Statut de variante</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantReference</branch>

                                                <container>MfgProductVariantReference</container>
                                                <tablePath>/root/RefVariantStatus</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- ProductVariantDescription Table -->
                <xs:element name="ProductVariantDescription" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Variant Descriptions</osd:label>
                            <osd:description>Variant Descriptions</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Descriptions de variante</osd:label>
                            <osd:description>Descriptions de variante</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/variantDescriptionId </primaryKeys>
                                <defaultLabel>${./variantDescriptionId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="variantDescriptionId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductVariantDescription.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductVariantDescription.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="variantId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Variant</osd:label>
                                        <osd:description>Product Variant</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Variante de produit</osd:label>
                                        <osd:description>Variante de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <tablePath>/root/ProductVariant</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="language" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Language</osd:label>
                                        <osd:description>Language</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Langue</osd:label>
                                        <osd:description>Langue</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Description</osd:label>
                                        <osd:description>Description</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Description</osd:label>
                                        <osd:description>Description</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- ProductVariantDimension Table -->
                <xs:element name="ProductVariantDimension" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Variant Dimensions</osd:label>
                            <osd:description>Variant Dimensions</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Dimensions de variante</osd:label>
                            <osd:description>Dimensions de variante</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/variantDimensionId </primaryKeys>
                                <defaultLabel>${./variantDimensionId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="variantDimensionId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductVariantDimension.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductVariantDimension.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="variantId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Variant</osd:label>
                                        <osd:description>Product Variant</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Variante de produit</osd:label>
                                        <osd:description>Variante de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <tablePath>/root/ProductVariant</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="dimensionType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Dimension Type</osd:label>
                                        <osd:description>Dimension Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de dimension</osd:label>
                                        <osd:description>Type de dimension</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgMaterialReference</branch>

                                                <container>MfgMaterialReference</container>
                                                <tablePath>/root/RefDimensionType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="value" type="xs:decimal" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Value</osd:label>
                                        <osd:description>Value</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Valeur</osd:label>
                                        <osd:description>Valeur</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- ProductMaterialRelationship Table -->
                <xs:element name="ProductMaterialRelationship" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Product Material Relationships</osd:label>
                            <osd:description>Product Material Relationships</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Relations produit-matériau</osd:label>
                            <osd:description>Relations produit-matériau</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/id </primaryKeys>
                                <defaultLabel>${./id}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductMaterialRelationship.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductMaterialRelationship.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="productVariant" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Variant</osd:label>
                                        <osd:description>Product Variant</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Variante de produit</osd:label>
                                        <osd:description>Variante de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantManagement</branch>

                                                <container>MfgProductVariantManagement</container>
                                                <tablePath>/root/ProductVariant</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="material" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Material</osd:label>
                                        <osd:description>Material</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Matériau</osd:label>
                                        <osd:description>Matériau</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgMaterialManagement</branch>

                                                <container>MfgMaterialManagement</container>
                                                <tablePath>/root/Material</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="relationshipType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Relationship Type</osd:label>
                                        <osd:description>Relationship Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de relation</osd:label>
                                        <osd:description>Type de relation</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantReference</branch>

                                                <container>MfgProductVariantReference</container>
                                                <tablePath>/root/RefProductMaterialRelationshipType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="product" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Master</osd:label>
                                        <osd:description>Product Master</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Produit parent</osd:label>
                                        <osd:description>Produit parent</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:inheritance>
                                            <sourceRecord>/root/ProductMaterialRelationship/productVariant</sourceRecord>
                                            <sourceNode>./productId</sourceNode>
                                        </osd:inheritance>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="plant" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Plant</osd:label>
                                        <osd:description>Plant</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Usine</osd:label>
                                        <osd:description>Usine</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgSitePlantManagement</branch>
                                                <container>MfgSitePlantManagement</container>
                                                <tablePath>/root/Site</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="isPrimary" type="xs:boolean" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Is Primary</osd:label>
                                        <osd:description>Is Primary</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Est principal</osd:label>
                                        <osd:description>Est principal</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="validFrom" type="xs:date" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Valid From</osd:label>
                                        <osd:description>Valid From</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Valide du</osd:label>
                                        <osd:description>Valide du</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="validTo" type="xs:date" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Valid To</osd:label>
                                        <osd:description>Valid To</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Valide au</osd:label>
                                        <osd:description>Valide au</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Status</osd:label>
                                        <osd:description>Status</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Statut</osd:label>
                                        <osd:description>Statut</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/LifecycleStatus</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>