<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:osd="urn:ebx-schemas:common_1.0" xmlns:fmt="urn:ebx-schemas:format_1.0" xmlns:ebxbnd="urn:ebx-schemas:binding_1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ebxs="urn:ebx-schemas:session_1.0">
    <xs:import namespace="urn:ebx-schemas:common_1.0" schemaLocation="https://schema.orchestranetworks.com/common_1.0.xsd"/>
    <xs:import namespace="urn:ebx-schemas:session_1.0" schemaLocation="https://schema.orchestranetworks.com/session_1.0.xsd"/>
    <xs:annotation>
        <xs:appinfo>
            <osd:validation/>
            <osd:inheritance>
                <dataSetInheritance>all</dataSetInheritance>
            </osd:inheritance>
            <ebxbnd:binding targetDirectory="../manufacturing-lib/src/main/java">
                <javaPathConstants typeName="com.onebx.ebx.fasttrack.manufacturing.path.MfgProductVariantComplianceManagementPaths">
                    <nodes root="/root" prefix="" relativeToRoot="false"/>
                </javaPathConstants>
            </ebxbnd:binding>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="root" osd:access="--">
        <xs:complexType>
            <xs:sequence>
                <!-- ProductVariantCompliance Table -->
                <xs:element name="ProductVariantCompliance" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Product Variant Compliance</osd:label>
                            <osd:description>Product Variant Compliance</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Conformité des variantes de produit</osd:label>
                            <osd:description>Conformité des variantes de produit</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/variantComplianceId </primaryKeys>
                                <defaultLabel>${./variantComplianceId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="variantComplianceId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductVariantCompliance.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductVariantCompliance.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="variantId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Variant</osd:label>
                                        <osd:description>Product Variant</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Variante de produit</osd:label>
                                        <osd:description>Variante de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantManagement</branch>

                                                <container>MfgProductVariantManagement</container>
                                                <tablePath>/root/ProductVariant</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="complianceCategory" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Compliance Category</osd:label>
                                        <osd:description>Compliance Category</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Catégorie de conformité</osd:label>
                                        <osd:description>Catégorie de conformité</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgReference</branch>

                                                <container>MfgReferenceData</container>
                                                <tablePath>/root/ComplianceCategory</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="complianceStatus" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Compliance Status</osd:label>
                                        <osd:description>Compliance Status</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Statut de conformité</osd:label>
                                        <osd:description>Statut de conformité</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantComplianceReference</branch>

                                                <container>MfgProductVariantComplianceReference</container>
                                                <tablePath>/root/RefProductComplianceStatus</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="effectiveStartDate" type="xs:date" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Effective Start Date</osd:label>
                                        <osd:description>Effective Start Date</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Date d'activation</osd:label>
                                        <osd:description>Date d'activation</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="effectiveEndDate" type="xs:date" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Effective End Date</osd:label>
                                        <osd:description>Effective End Date</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Date d'expiration</osd:label>
                                        <osd:description>Date d'expiration</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>