<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:osd="urn:ebx-schemas:common_1.0" xmlns:fmt="urn:ebx-schemas:format_1.0" xmlns:ebxbnd="urn:ebx-schemas:binding_1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ebxs="urn:ebx-schemas:session_1.0">
    <xs:import namespace="urn:ebx-schemas:common_1.0" schemaLocation="https://schema.orchestranetworks.com/common_1.0.xsd"/>
    <xs:import namespace="urn:ebx-schemas:session_1.0" schemaLocation="https://schema.orchestranetworks.com/session_1.0.xsd"/>
    <xs:annotation>
        <xs:appinfo>
            <osd:validation/>
            <osd:inheritance>
                <dataSetInheritance>all</dataSetInheritance>
            </osd:inheritance>
            <ebxbnd:binding targetDirectory="../manufacturing-lib/src/main/java">
                <javaPathConstants typeName="com.onebx.ebx.fasttrack.manufacturing.path.MfgProductClassificationManagementPaths">
                    <nodes root="/root" prefix="" relativeToRoot="false"/>
                </javaPathConstants>
            </ebxbnd:binding>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="root" osd:access="--">
        <xs:complexType>
            <xs:sequence>
                <!-- ProductClassification Table -->
                <xs:element name="ProductClassification" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Product Classifications</osd:label>
                            <osd:description>Product Classifications</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Classifications de produit</osd:label>
                            <osd:description>Classifications de produit</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/productClassificationId </primaryKeys>
                                <defaultLabel>${./productClassificationId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="productClassificationId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for ProductClassification.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour ProductClassification.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="productId" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product</osd:label>
                                        <osd:description>Product</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Produit</osd:label>
                                        <osd:description>Produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductManagement</branch>

                                                <container>MfgProductManagement</container>
                                                <tablePath>/root/Product</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="variantId" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Product Variant</osd:label>
                                        <osd:description>Product Variant</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Variante de produit</osd:label>
                                        <osd:description>Variante de produit</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductVariantManagement</branch>

                                                <container>MfgProductVariantManagement</container>
                                                <tablePath>/root/ProductVariant</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="classificationType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Classification Type</osd:label>
                                        <osd:description>Classification Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de classification</osd:label>
                                        <osd:description>Type de classification</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgProductClassificationReference</branch>

                                                <container>MfgProductClassificationReference</container>
                                                <tablePath>/root/RefProductClassificationType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="value" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Value</osd:label>
                                        <osd:description>Value</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Valeur</osd:label>
                                        <osd:description>Valeur</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>