<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:osd="urn:ebx-schemas:common_1.0" xmlns:fmt="urn:ebx-schemas:format_1.0" xmlns:ebxbnd="urn:ebx-schemas:binding_1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ebxs="urn:ebx-schemas:session_1.0">
    <xs:import namespace="urn:ebx-schemas:common_1.0" schemaLocation="https://schema.orchestranetworks.com/common_1.0.xsd"/>
    <xs:import namespace="urn:ebx-schemas:session_1.0" schemaLocation="https://schema.orchestranetworks.com/session_1.0.xsd"/>
    <xs:annotation>
        <xs:appinfo>
            <osd:validation/>
            <osd:inheritance>
                <dataSetInheritance>all</dataSetInheritance>
            </osd:inheritance>
            <ebxbnd:binding targetDirectory="../manufacturing-lib/src/main/java">
                <javaPathConstants typeName="com.onebx.ebx.fasttrack.manufacturing.path.MfgQualityManagementPaths">
                    <nodes root="/root" prefix="" relativeToRoot="false"/>
                </javaPathConstants>
            </ebxbnd:binding>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="root" osd:access="--">
        <xs:complexType>
            <xs:sequence>
                <!-- InspectionCharacteristic Table -->
                <xs:element name="InspectionCharacteristic" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Inspection Characteristics</osd:label>
                            <osd:description>Inspection Characteristics</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Caractéristiques d'inspection</osd:label>
                            <osd:description>Caractéristiques d'inspection</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/inspectionCharacteristicId </primaryKeys>
                                <defaultLabel>${./inspectionCharacteristicId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inspectionCharacteristicId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for InspectionCharacteristic.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour InspectionCharacteristic.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="characteristicType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Characteristic Type</osd:label>
                                        <osd:description>Characteristic Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de caractéristique</osd:label>
                                        <osd:description>Type de caractéristique</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefInspectionCharacteristicType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- InspectionMethod Table -->
                <xs:element name="InspectionMethod" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Inspection Methods</osd:label>
                            <osd:description>Inspection Methods</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Méthodes d'inspection</osd:label>
                            <osd:description>Méthodes d'inspection</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/inspectionMethodId </primaryKeys>
                                <defaultLabel>${./inspectionMethodId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inspectionMethodId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for InspectionMethod.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour InspectionMethod.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="methodType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Method Type</osd:label>
                                        <osd:description>Method Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de méthode</osd:label>
                                        <osd:description>Type de méthode</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefInspectionMethodType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- InspectionPlan Table -->
                <xs:element name="InspectionPlan" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Inspection Plans</osd:label>
                            <osd:description>Inspection Plans</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Plans d'inspection</osd:label>
                            <osd:description>Plans d'inspection</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/inspectionPlanId </primaryKeys>
                                <defaultLabel>${./inspectionPlanId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inspectionPlanId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for InspectionPlan.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour InspectionPlan.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="materialId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Material</osd:label>
                                        <osd:description>Material</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Matériel</osd:label>
                                        <osd:description>Matériel</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgMaterialManagement</branch>

                                                <container>MfgMaterialManagement</container>
                                                <tablePath>/root/Material</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="planStatus" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Plan Status</osd:label>
                                        <osd:description>Plan Status</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Statut du plan</osd:label>
                                        <osd:description>Statut du plan</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefInspectionPlanStatus</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- InspectionPlanStep Table -->
                <xs:element name="InspectionPlanStep" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Inspection Plan Steps</osd:label>
                            <osd:description>Inspection Plan Steps</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Étapes du plan d'inspection</osd:label>
                            <osd:description>Étapes du plan d'inspection</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/inspectionPlanStepId </primaryKeys>
                                <defaultLabel>${./inspectionPlanStepId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inspectionPlanStepId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for InspectionPlanStep.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour InspectionPlanStep.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="inspectionPlanId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Inspection Plan</osd:label>
                                        <osd:description>Inspection Plan</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Plan d'inspection</osd:label>
                                        <osd:description>Plan d'inspection</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <tablePath>/root/InspectionPlan</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="stepNumber" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Step Number</osd:label>
                                        <osd:description>Step Number</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Numéro d'étape</osd:label>
                                        <osd:description>Numéro d'étape</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- InspectionPlanCharacteristic Table -->
                <xs:element name="InspectionPlanCharacteristic" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Plan Characteristics Links</osd:label>
                            <osd:description>Plan Characteristics Links</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Liens caractéristiques du plan</osd:label>
                            <osd:description>Liens caractéristiques du plan</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/inspectionPlanCharacteristicId </primaryKeys>
                                <defaultLabel>${./inspectionPlanCharacteristicId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="inspectionPlanCharacteristicId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for InspectionPlanCharacteristic.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour InspectionPlanCharacteristic.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="inspectionPlanStepId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Plan Step</osd:label>
                                        <osd:description>Plan Step</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Étape du plan</osd:label>
                                        <osd:description>Étape du plan</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <tablePath>/root/InspectionPlanStep</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="inspectionCharacteristicId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Characteristic</osd:label>
                                        <osd:description>Characteristic</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Caractéristique</osd:label>
                                        <osd:description>Caractéristique</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <tablePath>/root/InspectionCharacteristic</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- SamplingProcedure Table -->
                <xs:element name="SamplingProcedure" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Sampling Procedures</osd:label>
                            <osd:description>Sampling Procedures</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Procédures d'échantillonnage</osd:label>
                            <osd:description>Procédures d'échantillonnage</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/samplingProcedureId </primaryKeys>
                                <defaultLabel>${./samplingProcedureId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="samplingProcedureId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for SamplingProcedure.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour SamplingProcedure.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sampleSize" type="xs:decimal" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Sample Size</osd:label>
                                        <osd:description>Sample Size</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Taille de l'échantillon</osd:label>
                                        <osd:description>Taille de l'échantillon</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- QualitySpecification Table -->
                <xs:element name="QualitySpecification" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Quality Specifications</osd:label>
                            <osd:description>Quality Specifications</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Spécifications de qualité</osd:label>
                            <osd:description>Spécifications de qualité</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/qualitySpecificationId </primaryKeys>
                                <defaultLabel>${./qualitySpecificationId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="qualitySpecificationId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for QualitySpecification.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour QualitySpecification.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="specificationType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Specification Type</osd:label>
                                        <osd:description>Specification Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de spécification</osd:label>
                                        <osd:description>Type de spécification</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefSpecificationType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- DefectCode Table -->
                <xs:element name="DefectCode" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Defect Codes</osd:label>
                            <osd:description>Defect Codes</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Codes de défaut</osd:label>
                            <osd:description>Codes de défaut</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/defectCodeId </primaryKeys>
                                <defaultLabel>${./defectCodeId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="defectCodeId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for DefectCode.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour DefectCode.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="defectCategory" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Defect Category</osd:label>
                                        <osd:description>Defect Category</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Catégorie de défaut</osd:label>
                                        <osd:description>Catégorie de défaut</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefDefectCategory</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- DefectCodeGroup Table -->
                <xs:element name="DefectCodeGroup" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Defect Code Groups</osd:label>
                            <osd:description>Defect Code Groups</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Groupes de codes de défaut</osd:label>
                            <osd:description>Groupes de codes de défaut</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/defectCodeGroupId </primaryKeys>
                                <defaultLabel>${./defectCodeGroupId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="defectCodeGroupId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for DefectCodeGroup.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour DefectCodeGroup.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="defectCodeId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Defect Code</osd:label>
                                        <osd:description>Defect Code</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code de défaut</osd:label>
                                        <osd:description>Code de défaut</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <tablePath>/root/DefectCode</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- QualityCertificateRequirement Table -->
                <xs:element name="QualityCertificateRequirement" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Certificate Requirements</osd:label>
                            <osd:description>Certificate Requirements</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Exigences de certificat</osd:label>
                            <osd:description>Exigences de certificat</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/qualityCertificateRequirementId </primaryKeys>
                                <defaultLabel>${./qualityCertificateRequirementId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="qualityCertificateRequirementId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for QualityCertificateRequirement.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour QualityCertificateRequirement.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="certificateType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Certificate Type</osd:label>
                                        <osd:description>Certificate Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type de certificat</osd:label>
                                        <osd:description>Type de certificat</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefCertificateType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- MaterialQualityRequirement Table -->
                <xs:element name="MaterialQualityRequirement" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Material Quality Requirements</osd:label>
                            <osd:description>Material Quality Requirements</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Exigences qualité matériel</osd:label>
                            <osd:description>Exigences qualité matériel</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/materialQualityRequirementId </primaryKeys>
                                <defaultLabel>${./materialQualityRequirementId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="materialQualityRequirementId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for MaterialQualityRequirement.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour MaterialQualityRequirement.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="materialId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Material</osd:label>
                                        <osd:description>Material</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Matériel</osd:label>
                                        <osd:description>Matériel</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgMaterialManagement</branch>

                                                <container>MfgMaterialManagement</container>
                                                <tablePath>/root/Material</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="requirementType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Requirement Type</osd:label>
                                        <osd:description>Requirement Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type d'exigence</osd:label>
                                        <osd:description>Type d'exigence</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefQualityRequirementType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- SupplierQualityRequirement Table -->
                <xs:element name="SupplierQualityRequirement" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Supplier Quality Requirements</osd:label>
                            <osd:description>Supplier Quality Requirements</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Exigences qualité fournisseur</osd:label>
                            <osd:description>Exigences qualité fournisseur</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/supplierQualityRequirementId </primaryKeys>
                                <defaultLabel>${./supplierQualityRequirementId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="supplierQualityRequirementId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for SupplierQualityRequirement.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour SupplierQualityRequirement.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="supplierId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Supplier</osd:label>
                                        <osd:description>Supplier</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Fournisseur</osd:label>
                                        <osd:description>Fournisseur</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgSupplierManagement</branch>

                                                <container>MfgSupplierManagement</container>
                                                <tablePath>/root/Supplier</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="requirementType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Requirement Type</osd:label>
                                        <osd:description>Requirement Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type d'exigence</osd:label>
                                        <osd:description>Type d'exigence</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefQualityRequirementType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- CustomerQualityRequirement Table -->
                <xs:element name="CustomerQualityRequirement" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Customer Quality Requirements</osd:label>
                            <osd:description>Customer Quality Requirements</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Exigences qualité client</osd:label>
                            <osd:description>Exigences qualité client</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/customerQualityRequirementId </primaryKeys>
                                <defaultLabel>${./customerQualityRequirementId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="customerQualityRequirementId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for CustomerQualityRequirement.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour CustomerQualityRequirement.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="customerId" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Customer</osd:label>
                                        <osd:description>Customer</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Client</osd:label>
                                        <osd:description>Client</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgCustomerManagement</branch>

                                                <container>MfgCustomerManagement</container>
                                                <tablePath>/root/Customer</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="requirementType" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Requirement Type</osd:label>
                                        <osd:description>Requirement Type</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Type d'exigence</osd:label>
                                        <osd:description>Type d'exigence</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>BMfgQualityReference</branch>

                                                <container>MfgQualityReference</container>
                                                <tablePath>/root/RefQualityRequirementType</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- QualitySourceReference Table -->
                <xs:element name="QualitySourceReference" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation xml:lang="en-US">
                            <osd:label>Quality Source References</osd:label>
                            <osd:description>Quality Source References</osd:description>
                        </xs:documentation>
                        <xs:documentation xml:lang="fr-FR">
                            <osd:label>Références sources de qualité</osd:label>
                            <osd:description>Références sources de qualité</osd:description>
                        </xs:documentation>
                        <xs:appinfo>
                            <osd:table>
                                <primaryKeys>/qualitySourceReferenceId </primaryKeys>
                                <defaultLabel>${./qualitySourceReferenceId}</defaultLabel>
                            </osd:table>
                        </xs:appinfo>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="qualitySourceReferenceId" minOccurs="1" maxOccurs="1" osd:trim="onUserInput">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Primary Key for QualitySourceReference.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>ID</osd:label>
                                        <osd:description>Clé primaire pour QualitySourceReference.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sourceSystemName" type="xs:string" minOccurs="1" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System Name</osd:label>
                                        <osd:description>Source System Name</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Nom du système source</osd:label>
                                        <osd:description>Nom du système source</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="sourceSystem" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>Source System</osd:label>
                                        <osd:description>The origin system of this record.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Système source</osd:label>
                                        <osd:description>Le système d'origine.</osd:description>
                                    </xs:documentation>
                                    <xs:appinfo>
                                        <osd:otherFacets>
                                            <osd:tableRef>
                                                <branch>CommonReferenceData</branch>

                                                <container>CommonReferenceData</container>
                                                <tablePath>/root/SourceSystem</tablePath>
                                            </osd:tableRef>
                                        </osd:otherFacets>
                                    </xs:appinfo>
                                </xs:annotation>
                            </xs:element>
                            <xs:element name="externalCode" type="xs:string" minOccurs="0" maxOccurs="1">
                                <xs:annotation>
                                    <xs:documentation xml:lang="en-US">
                                        <osd:label>External Code</osd:label>
                                        <osd:description>The mapped code in the source system.</osd:description>
                                    </xs:documentation>
                                    <xs:documentation xml:lang="fr-FR">
                                        <osd:label>Code externe</osd:label>
                                        <osd:description>Le code dans le système source.</osd:description>
                                    </xs:documentation>
                                </xs:annotation>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>